### ISSUE TITLE
Unable to do anything in Version Control tab and General Messages Tab

### ISSUE THREAD

**Issue by kbrydges** [forio/julia-studio#104]
Hello-
  On Mac/Chrome/Julia 0.3.2, in the Julia Studio, when I click on the Version Control Tab/General Messages Tab, I am unable to do anything. Perhaps I am not understanding the functionality but it does not seem very intuitive. See Screenshot. 
![JuliaVersionControl](https://f.cloud.github.com/assets/3923808/282830/b2d9973c-919d-11e2-8e89-75c8b5877a7f.png)

Thanks-
Kat

**Comment by WestleyArgentum** [comment]
We should consider doing some ui work on these, but they're actually working as expected. Basically these are consoles where version control and general information show up occasionally and with no warning (not that you'd ever know that, because you'd never come here, because you can't do anything useful here... ya)
