### ISSUE TITLE
Win 7: Julia interpreter crashes on startup (IDE does not work as expected)

### ISSUE THREAD

**Issue by m0nzderr** [forio/julia-studio#123]
I did a fresh intall of julia-studio-0.3.1 for windows. The IDE itself seems to work fine, but scripts definitely do not work (no reaction on "Run" command) nor the console (I can type into it, but no "julia>" prompt appears and no response follows). 

Then I tried to run julia.bat from /julia-studio/julia/bin directory. And tha't what I got as the output:

```
C:\...Files (x86)\JuliaStudio-0.3.1\julia-studio\julia\bin>julia.bat

0x02320205 (0x00000000 0x00000000 0x0028FDF8 0x6F40B44D) <unknown module>
0x023201CB (0x02E76DF0 0x00000000 0x00000000 0x00000000) <unknown module>
0x6F40B44D (0x02E76C80 0x00000000 0x00000000 0x76988CD5), jl_apply_generic() + 0x5D bytes(s)
0x00401888 (0x00000000 0x00BF7F84 0x00000003 0x00000004)
0x6F44131F (0x00000000 0x00BF7F84 0x00401760 0x00BF2D78), julia_trampoline() + 0x4F bytes(s)
0x0041A7B5 (0x00000000 0x00BF7F84 0x00BF1A08 0x00000000), jl_clear_input() + 0x16AE5 bytes(s)
0x004013EA (0x7EFDE000 0x0028FFD4 0x77519D72 0x7EFDE000)
0x750C3677 (0x7EFDE000 0x7769641F 0x00000000 0x00000000), BaseThreadInitThunk() + 0x12 bytes(s)
0x77519D72 (0x004014D0 0x7EFDE000 0x00000000 0x00000000), RtlInitializeExceptionChain() + 0x63 bytes(s)
0x77519D45 (0x004014D0 0x7EFDE000 0x00000000 0x78746341), RtlInitializeExceptionChain() + 0x36 bytes(s)
```

It didn't feel like an expected behavior. 

I also tried a different script like /julia-studio/julia/julia.bat, played a bit with prepare-julia-env.bat, but the results are the same.

I'm running Win 7 x64 Ultimate on i5 CPU. 

Any clues?

UPD: Installed on a different Win 7 machine, it all worked. But still can't make it run on my PC.

**Comment by WestleyArgentum** [comment]
That's definitely not expected behavior...

It looks like Julia isn't working on your machine, two things that might help jump to mind:
1. Maybe your machine isn't running Julia in 32bit compatibility mode. You could try right-clicking on ./julia-studio/julia/bin/julia-release-readline, going to "properties", and checking the "compatibility" tab. Unfortunately there isn't yet a stable release of 64bit Julia on Windows.
2. Maybe there's a bug with the version of Julia we shipped with the IDE. You could try downloading version 0.1.2 for Windows here: https://code.google.com/p/julialang/downloads/list and, if that runs, you can point the ide at the new Julia. Either copy the over the "julia" dir in "julia-studio" or go to Tools->Options->Julia and point at the directory containing the new "julia.bat"

**Comment by WestleyArgentum** [comment]
Much has changed since this was a problem and 64 bit Julia binaries are available. Try those out, if there are problems then check out issue #139
