### ISSUE TITLE
Using MAT package errors

### ISSUE THREAD

**Issue by murphsp1** [forio/julia-studio#128]
julia> using MAT
syntax: extra token after end of expression
at /Users/murphsp1/.julia/HDF5/src/plain.jl:427
at /Users/murphsp1/.julia/HDF5/src/HDF5.jl:1
at /Users/murphsp1/.julia/MAT/src/MAT_HDF5.jl:30
at /Users/murphsp1/.julia/MAT/src/MAT.jl:25

**Comment by murphsp1** [comment]
Julia version 0.3.2

**Comment by WestleyArgentum** [comment]
Indeed it does... The issue seems to be with a dependency of the MAT package, namely HDF5. It looks like compatibility with different versions of Julia didn't get spelled out properly on the master branch of METADATA.jl

I've submitted a pull request that I hope will fix the problem here: https://github.com/JuliaLang/METADATA.jl/pull/287

If that doesn't work I think your best bet is to poke the maintainers of HDF5 (https://github.com/timholy/HDF5.jl) or MAT (https://github.com/simonster/MAT.jl)

Closing for now, but let us know if you have any other problems
