### ISSUE TITLE
Problem with if else in Julia

### ISSUE THREAD

**Issue by Lytu** [forio/julia-studio#259]
When i do:
M=rand(5,5)
a=M[:,1]' \* M[:,1]
if a<0
        println("Less than 0")
else
        println("more")
end

I have an error: " isless has no method matching isless(::Array{Float64,2}, ::Int 32) in < at operators.jl:32

Can anyone tell me please how to do this? Thank you

**Comment by WestleyArgentum** [comment]
I'm not sure exactly what you're trying to do, but you're problem is with `a=M[:,1]' * M[:,1]`. I recommend you print that value out -- it ends up being a multidimensional array, not a number. Docs here: http://docs.julialang.org/en/release-0.3/manual/arrays/

And again, in the future, it's best to ask things on the users group (https://groups.google.com/forum/#!forum/julia-users) because very few people will see them here.
