### ISSUE TITLE
Easier update process

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#61]
The update process could be more seamless. It's annoying to have to go and download the update every time. Should update in background.

**Comment by pygy** [comment]
That would sure be nice. 

It would also be nice to have daily builds of Julia available, or to install older versions of the packages. 

Currently, the Tk package doesn't work because it relies on a new version of the base library.

**Comment by WestleyArgentum** [comment]
Ya, we need to update the version of julia we ship. We haven't found a way to install older versions of the packages because, of course, they're all unversioned. In my opinion, 0.1 cannot come soon enough :)

You can point julia studio at your own version of juila, however. See JuliaStudio->Preferences->Julia->PathToBinaries. It expects a folder equivalent to the top level "julia" folder of a binary release, so "usr" if you build from source.

**Comment by pygy** [comment]
> We haven't found a way to install older versions of the packages because, of course, they're all unversioned.

Perhaps the commit id?

**Comment by WestleyArgentum** [comment]
I thought the same thing, but I think it's too opaque. Users could understandably be confused when they update and don't get the cool features they see online, and for users who want to work on the packages it would be annoying (although, they could probably be expected to go to the command line and update themselves...)

**Comment by WestleyArgentum** [comment]
I think the bottom line here is that I need to be better about keeping up to date with Julia builds

**Comment by pygy** [comment]
:-)

**Comment by waldyrious** [comment]
related: #48

**Comment by waldyrious** [comment]
There should also be an option in the installer to remove the previously installed version.

**Comment by WestleyArgentum** [comment]
Good idea, I broke it off so we don't forget

**Comment by keesvp** [comment]
irrelevant history.
