### ISSUE TITLE
Remove splash screen at start up

### ISSUE THREAD

**Issue by mpbean** [forio/julia-studio#64]
The start up splash screen slows down productivity and is unnecessary.

**Comment by pygy** [comment]
I suppose you're on Windows or Linux, since there's no splash screen here on OS X, but I wouldn't mind having one.

Julia Studio takes ~1 second to load from SSD (Core i5), probably longer when loading from a hard disk. It is IMO appropriate for Forio to toot their horn during that time (or even a bit longer).

**Comment by WestleyArgentum** [comment]
I think he actually means the first page that Julia Studio opens to. Maybe the "Welcome page". It's big and mostly blank with a list of recently open files.

We think it might be nicer to open Julia Studio and immediately be presented with a console and any files you had open when you were last working.

**Comment by adambom** [comment]
Agreed

**Comment by WestleyArgentum** [comment]
Fixed as of 2bfc7a20ec784a7705d1624fa47ee1ba0978bf78

**Comment by adambom** [comment]
Sweet
