### ISSUE TITLE
Homemade Julia studio doesn't find Julia information?

### ISSUE THREAD

**Issue by scotttetrick1357** [forio/julia-studio#68]
I have downloaded and built the source version of Julia Studio 0.2.6.  When I try to open the console window, I get:

dyld: Library not loaded: @rpath/libjulia-release.dylib
  Referenced from: /Users/stetrick/julia/bin/julia-release-basic
  Reason: image not found
Error: Julia crashed unexpectedly.
It's still a young language, this can happen from time to time.
Please reset the console and try again...

The location is where I have built Julia.  Are there some paths or steps I'm missing?

Thanks

**Comment by WestleyArgentum** [comment]
Hmm, sorry about that.
Do you see a file called `sys.ji` inside `julia/lib/julia/`?

It's also possible that we're behind some change in the version of Julia you built...
If you right-click and open the JuliaStudio.app that we ship, you should see a folder called `julia`. What happens if you go to `JuliaStudio->Preferences->Julia->PathToBinaries` and point at a copy of that folder?

**Comment by scotttetrick1357** [comment]
There is no lib directory in the Julia directory that I built.  julia is a link to the julia/bin/julia-release-basic.  When I copy the sys.jl (which is alone in a ... /julia/usr/lib directory) into the julia directory, get a different answer about STDIN not supported, and an error about being unable to open pkg.jl.

**Comment by WestleyArgentum** [comment]
Ah, I see. Alright, to be totally transparent about how the ide fires up the julia process, it expects to be pointed at the top level of a would-be binary release of Julia. In other words, if you download a binary version of Julia it expects to be pointed at the root folder (which, conveniently enough, is called "julia"). If you build julia from source, the equivalent folder is called "usr" (it contains "bin", "lib", etc).

So just go to `JuliaStudio->Preferences->Julia->PathToBinaries`, point to the `usr` folder, and you should be good to go.

**Comment by scotttetrick1357** [comment]
I had to make some other links here.  It needed a pkg directory down the Julia Studio path, as well as pkg.jl and Git.jl, which I lined to the appropriate files in the julia/base from the julia build.  Now I can get the console to run without a startup error.

**Comment by WestleyArgentum** [comment]
Well, linking certainly can work, but be warned, many things may not work if Julia can't find them.

In particular, there are supposed to be files inside that `pkg` folder and I'm afraid that you'll be unable to add any packages, etc, without them.

**Comment by scotttetrick1357** [comment]
Would you suggest that the entire contents of the Julia/pkg directory get copied to the JuliaStudio pkg directory?  It seems that the directory it looks at is not based on the execution location for julia.

**Comment by WestleyArgentum** [comment]
Well, I'm not exactly sure what your setup looks like... Basically, I'm assuming you have a build of Julia Studio somewhere and you have a clone of Julia built.

If you run your build of Julia Studio, and go up to the `JuliaStudio` menu at the top, you should be able to find `JuliaStudio->Preferences->Julia->PathToBinaries`. I would try setting this path to `/path/to/julia-clone/usr` (in other words, the usr directory that was created when you built Julia).

That should let you run your version of julia in the ide. If you get encounter more problems it's most likely because the version of Julia that the ide expects is a bit behind. In that case you can checkout an older commit or point Julia Studio at unzipped [binaries from the julia website](http://code.google.com/p/julialang/downloads/detail?name=julia-ba9eb0a653-Darwin-x86_64.tar.gz&can=2&q=)

**Comment by WestleyArgentum** [comment]
This is old, much has changed
