### ISSUE TITLE
include does not work as expected

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#85]
Step 1) cd to ~

`cd("~")`

Step 2) Create a file ~/blah.jl

Step 3) Add some code to blah.jl in Julia Studio

`blah(x) = x + 1`

Step 4) Include the file via command line

`include("blah")`

Expected response is no error, and blah is defined

Actual response is: `could not open file /Applications/JuliaStudio.app/Contents/Resources/juliaengine/blah`

Check to make sure I'm the right directory:

`pwd()`

returns ~

Using the run button works, but the include command called directly from the command line always looks in the juliaengine directory.

**Comment by StefanKarpinski** [comment]
Can you put `@show Base.source_path()` in there somewhere to print where Julia thinks it should be loading files? Include is always done relative to the current source path, which initially starts as the current working directory, but could diverge over time. I also just made a change so that new tasks correctly inherit their notion of the current source path from their parent task, but that might have broken something.

**Comment by adambom** [comment]
Base.source_path() => "/Applications/JuliaStudio.app/Contents/Resources/juliaengine/main.jl"
"/Applications/JuliaStudio.app/Contents/Resources/juliaengine/main.jl"

**Comment by WestleyArgentum** [comment]
This is using Julia v0.1, so don't worry about potential recent breakage. Maybe I should be managing SOURCE_PATH so include works as expected in the console... I'll look into that.

**Comment by WestleyArgentum** [comment]
We change directories dynamically now and have an issue #132 for making the current stuff better
