### ISSUE TITLE
Antialiasing on Linux

### ISSUE THREAD

**Issue by WestleyArgentum** [forio/julia-studio#95]
From the feedback form:

> The GUI is aliased even if I check antialiasing in the settings menu (fonts).
> I am using XUbuntu 12.10. It works fine with Windows 7.
> This occurs with Julia Studio 0.3.0 and 0.3.1.

Antialiasing works for me on regular Ubuntu 12.04, I'm downloading XUbuntu to check it out.

**Comment by lecorre** [comment]
same problem here with Ubuntu 12.10 64bits (Unity) and Julia Studio 0.3.1
![juliastudio-aliasing](https://f.cloud.github.com/assets/3392149/259208/9fd1c14a-8cb7-11e2-9fdc-7b095382eb8b.png)

It seems to be fixed with Qt 4.8.2 according to this page
http://qt-project.org/forums/viewthread/16819

X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0

**Comment by WestleyArgentum** [comment]
We're going to make a push to update, but before that happens, building from source has solved the problem for other people.

**Comment by WestleyArgentum** [comment]
We're pretty sure this is a fallback library issue, but we haven't pinned down exactly what we need to ship with the linux distro

**Comment by gaborbernat** [comment]
No update on this yet?

**Comment by stuinzuri** [comment]
@gaborbernat We are wrapping up a long and painful port to Qt5 (from Qt4).  In theory this will resolve the antialiasing issue, along with a host of other GUI issues.  While the core porting work is done, it necessitated a patch to Qt itself which won't be released until Qt 5.3, so we need to work some build magic to get everything working together and distributable. "Soon."

**Comment by stuinzuri** [comment]
Just got the build working a few minutes ago, and this issue is looking resolved.

With (the default):
![julia-studio_issue-95-with](https://f.cloud.github.com/assets/172643/1812845/0686c544-6e93-11e3-8083-1df3d6d4408c.png)

And now without:
![julia-studio_issue-95-without](https://f.cloud.github.com/assets/172643/1812846/149f29dc-6e93-11e3-98ac-c56ffbdef894.png)

We expect to have the new build up in the next week or so.  I'll close it once we release 0.4.4.

**Comment by stuinzuri** [comment]
released
